# Steps
# 1. Prepare environment
#   a. Install DirectXSDK(June 2010)
#   b. Install Visual Studio 2019 Environment
# 2. Issue Release on GitHub using generated ZIP
# 3. Build and Compile docs and place in /docs folder

name: Release EOP on GitHub

on:
  push:
    branches:
      - "test-eop-release"

jobs:
  prepare-environment:
    runs-on: windows-latest
    steps:
    - uses: ilammy/msvc-dev-cmd@v1

    - name: Checkout Source
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Check Project State
      run: dir

    - name: Setup cache
      id:   cache
      uses: actions/cache@v1
      with:
        path: ~/cache
        key:  cache

    - name:  Set DXSDK_DIR env variable
      run:   echo ::set-env name=DXSDK_DIR::$HOME/cache/
      shell: bash

    - name:  Download and cache DirectX SDK
      if:    steps.cache.outputs.cache-hit != 'true'
      run:   |
            curl -L https://download.microsoft.com/download/a/e/7/ae743f1f-632b-4809-87a9-aa1bb3458e31/DXSDK_Jun10.exe -o _DX2010_.exe
            7z x _DX2010_.exe DXSDK/Include -o_DX2010_
            7z x _DX2010_.exe DXSDK/Lib/x86 -o_DX2010_
            mv _DX2010_/DXSDK $HOME/cache
            rm -fR _DX*_ _DX*_.exe
      shell: bash
    # - name: Install DirectX SDK with Chocolatey
    #   run: choco install directx-sdk

    - name: Install Visual Studio 2019 Community with Chocolatey
      run: choco install visualstudio2019community

    - name: Run buildEOP.ps1
      run: |
        ./buildEOP.ps1

    # - name: Release new EOP version on GitHub
    # - uses: "marvinpinto/action-automatic-releases@latest"
    #   with:
    #     repo_token: "${{ secrets.GITHUB_TOKEN }}"
    #     automatic_release_tag: "latest"
    #     title: "M2TWEOP-2.1.beta.${{ secrets.BETA_VERSION}}.7z"
    #     files: |
    #       dist/M2TWEOP-2.1.beta.${{ secrets.BETA_VERSION}}.7z