# Steps
# 1. Prepare environment
#   a. Install DirectXSDK(June 2010)
#   b. Install Visual Studio 2019 Environment
# 2. Issue Release on GitHub using generated ZIP
# 3. Build and Compile docs and place in /docs folder

name: Release EOP on GitHub

on: [push, pull_request]

env:
  COMMIT_MESSAGE: ${{ github.event.head_commit.message }}

jobs:
  build-eop:
    runs-on: windows-latest
    steps:
    - uses: ilammy/msvc-dev-cmd@v1

    - name: "Checkout from latest commit: ${{ github.event.head_commit.message }}"
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Show checked out files
      run: ls -l
      shell: bash

    - name: Setup DirectX Cache
      id:   dxcache
      uses: actions/cache@v1
      with:
       path: DXSDK
       key:  dxsdk-cache

    - name:  Download DirectX SDK if not cached
      if:    steps.dxsdk-cache.outputs.cache-hit != 'true'
      run:   |
            curl -L https://download.microsoft.com/download/a/e/7/ae743f1f-632b-4809-87a9-aa1bb3458e31/DXSDK_Jun10.exe -o _DX2010_.exe
            7z -y x _DX2010_.exe DXSDK
            rm -fR _DX*_ _DX*_.exe
      shell: bash

    - name: Install Visual Studio 2019 Community with Chocolatey
      run: choco install visualstudio2019community

    - name: Run buildEOP.ps1
      run: |
        ./buildEOP.ps1
      env:
        DXSDK_DIR: ${{ github.workspace }}\DXSDK\

    - name: Check Project State after completion
      run: ls -l
      shell: bash

  # If the latest commit message starts with 'Release', issue a release on GitHub
  if: startsWith(${{ github.event.head_commit.message }}, 'Release')
  release-eop:
    needs: build-eop
    runs-on: windows-latest
    steps:
    - name: Release new EOP version on GitHub
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        title: "M2TWEOP-Github-generated.zip"
        files: M2TWEOP.zip
